services:
  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://analytics_user:analytics_pass@postgres:5432/analytics_db
      - ENVIRONMENT=development
    depends_on:
      - postgres
    volumes:
      - ./api/app:/app/app  # Hot reload for FastAPI code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
  
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=analytics_db
      - POSTGRES_USER=analytics_user
      - POSTGRES_PASSWORD=analytics_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5433:5432"  # Exposed for GUI tools like pgAdmin, DBeaver, etc.
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initial schema
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test-site:/usr/share/nginx/html:ro  # Serve test website
    depends_on:
      - fastapi
    restart: unless-stopped

volumes:
  postgres_data:
